### PR TITLE
UI optimize and Code optimize

### PR DESCRIPTION
**Pull request by Mxdcq**
(1) I found it is better to use `$scope` when I try to fix issue 7, so I injected `$scope` in `event.controller.js` and then use `$scope` instead of `vm`. Unfortunately, issue 7 is still pending.
(2) After discussion with Junyi, I changed the entry style of our app.
(3) I found that if we try to add more static data into 'mock.events.json', the results of 'sidenav' and 'md-card' is ruined. It will look like this: 
screen shot 2016-12-13 at 2 13 05 am
So I change the UI style to fix this. And I also extend the width of 'sidenav' to 100%.

### CODE REVIEW

**Comment by antti-TIEA4** [comment]
> (1) I found it is better to use $scope when I try to fix issue 7, so I injected $scope in event.controller.js and then use $scope instead of vm. Unfortunately, issue 7 is still pending.

How exactly using `$scope` helps you to achieve what you are trying to do? You are just referencing to the same namespace but added yet another extra layer to get there. We do not need `$scope`, we can already reference to it via the controller as syntax.

> (2) After discussion with Junyi, I changed the entry style of our app.

This seems to have removed the feature where the user can see three nearby events in the app list. I do not understand why we would want to do that.

> (3) I found that if we try to add more static data into 'mock.events.json', the results of 'sidenav' and 'md-card' is ruined. It will look like this:

Yeah, that's a good catch. The changes in this PR that fix this issue are

- removing from `index.html`
  * `layout="column"` on line 47
  * `layout-fill` on line 48

- changing/adding to `style.css`s `.event-list` selector
  * `height: 150px;`
  * `margin: 0;`

I'd like to accept those changes from this PR.

**Comment by Mxdcq** [comment]
(1) https://github.com/angular/angular.js/wiki/When-to-use-$scope.$apply(), http://jimhoskins.com/2012/12/17/angularjs-and-apply.html. There are two links, which tell me $scope.$apply() can detect an asynchronous event and return new value. I hope I am under a right way to fix this.
(2) Because 'three nearby events' is the content of our app. When I try to add a 'show more' link or button, I found it is located in the main index.html not our app's index.html through Google Chrome Debug Tool. Then Junyi told me it is the entry button of our app. For example, if a user install "weather", "city info", "upcoming" apps, then there will be a 3 button of them, after clicking one of the button, the user can use the function of that app. So I think we should provide the App title on this button rather than part of our function.

**Comment by antti-TIEA4** [comment]
> (1) https://github.com/angular/angular.js/wiki/When-to-use-$scope.$apply(), http://jimhoskins.com/2012/12/17/angularjs-and-apply.html. There are two links, which tell me $scope.$apply() can detect an asynchronous event and return new value.

Quote from your first link:
> Do NOT randomly sprinkle it throughout your code.

Why do you want to use `$scope.apply()`? We have absolutely no need for it here. Angular creates watchers automatically for those variables anyway.

> (2) Because 'three nearby events' is the content of our app. When I try to add a 'show more' link or button, I found it is located in the main index.html not our app's index.html through Google Chrome Debug Tool. Then Junyi told me it is the entry button of our app. For example, if a user install "weather", "city info", "upcoming" apps, then there will be a 3 button of them, after clicking one of the button, the user can use the function of that app. So I think we should provide the App title on this button rather than part of our function.

The tile mode is designed to have a mini view of the content of the app. If you are trying to fix #7 it should be a simple `style.css` and `index.html` change. Without seeing the code that you have tried and doesn't work, I can't say why it doesn't work.

**Comment by Mxdcq** [comment]
(1) I can remove $scope and do it like before. I am getting into trouble with issue-44.
(2) Now it looks like this, and I sent you a short video on slack.
screen shot 2016-12-13 at 3 48 24 pm

**Comment by antti-TIEA4** [comment]
10 min trial and error with CSS
screenshot from 2016-12-13 16-43-58

**Comment by Mxdcq** [comment]
I am also trying.

**Comment by Mxdcq** [comment]
screen shot 2016-12-13 at 4 52 15 pm
Is this what you want?

**Comment by antti-TIEA4** [comment]
> screen shot 2016-12-13 at 4 52 15 pm
> Is this what you want?

Not really. I posted an example of what it could look like in my previous comment.

**Comment by Mxdcq** [comment]
image
You mean this one?
I think it is similar with mine.
image

**Comment by antti-TIEA4** [comment]
> You mean this one?
> I think it is similar with mine.

The difference is that the other one does not remove the three events.
As my 10 min test shows, it is possible to display both the events and an additional text.

**Comment by Mxdcq** [comment]
You mean make the events vague and the app name cover on them?

**Comment by Mxdcq** [comment]
screen shot 2016-12-13 at 9 18 46 pm
Try my best.

**Comment by antti-TIEA4** [comment]
The same way you added the distance text to the card [before](https://github.com/APT-project/upcoming/commit/917f816e2dfbd0bb93a03779af6ea6f89efb2783), the same way you can add an element that says "tap for more" or something similar.
You can do it :+1:

**Comment by Mxdcq** [comment]
The distance is on every card because of the `ng-reapte` tag. So add "tap for more" on each card?

**Comment by antti-TIEA4** [comment]
One is enough. You can add it on the outer element `<md-content>`

**Comment by Mxdcq** [comment]
screen shot 2016-12-13 at 10 10 45 pm
How about this one?

**Comment by antti-TIEA4** [comment]
The original layout with three events and then a "show more" etc. element.

**Comment by Mxdcq** [comment]
The commit message should be "remove $scope and change the tile stlye to the orginal one"

**Comment by antti-TIEA4** [comment]
There are so many unrelated changes as the first commits tried to do something else. I think it's best if we close this, and you make a brand new branch and create a new PR based on that.

-----------

You could just replace the last card with a "show more" hint like this
screenshot from 2016-12-14 01-38-59
Or something in that direction. Main idea is that we want to have a preview of the events in the tile mode. But we also need to tell the users that the tiles should be touched to see more.

**Pull request closed without merging**
