### PR TITLE
General UI updates, colors and a new marker

### PR DESCRIPTION
**Pull request by heinoapt**

### CODE REVIEW

**Comment by antti-TIEA4** [comment]
Should we use the markers @johwoh did, or was https://github.com/heinoapt/upcoming/blob/3fc3c7bb22c47758b1171d601cbc35c738ea4f42/app/img/icons/marker.event.png one of those?

**Comment by antti-TIEA4** [comment]
I mean these 
https://www.dropbox.com/sh/iwukijrcvwxlsra/AAC7t2KCQahsiegmeooJ_eJSa?dl=0

**Comment by antti-TIEA4** [comment]
But we can add those different color extra markers later.

In any case, this looks (very) good to me. :shipit:

**Comment by heinoapt** [comment]
Yeah, let's add them later. I actually didn't notice those.

Great, thanks!

**Pull request merged**
