### PR TITLE
add distance to tiles, make events more meaningful

### PR DESCRIPTION
**Pull request by Mxdcq**
If this commit is merged, I will work on issue-55 "improve the look of tiles".

### CODE REVIEW

**Comment by heinoapt** [comment]
Looks good. This is applying the already working distance to the tiles?

**Comment by Mxdcq** [comment]
Yes, you are right.

**Comment by heinoapt** [comment]
Ok. I understood the PR correctly then.

**Comment by antti-TIEA4** [comment]
@Mxdcq This does not work because you made your changes on top of a 21 days old version of the app. See: https://github.com/Mxdcq/upcoming/commits/issue-56

Next time please update your local repository before introducing changes :)

**Comment by heinoapt** [comment]
Yeah, seems like the distance doesn't show up.

**Comment by Mxdcq** [comment]
I found it does not work when I update it. How to fix it now?

**Comment by antti-TIEA4** [comment]
@Mxdcq You used the old version of the distance filter.
Console: https://docs.angularjs.org/error/$injector/unpr?p0=distanceFormatFilterProvider%20%3C-%20distanceFormatFilter

**Comment by heinoapt** [comment]
@Mxdcq check Slack for the updating!

**Comment by antti-TIEA4** [comment]
@Mxdcq Just update to the latest version, then create a new branch from it and do the same stuff you did here, test, and submit a new PR.

**Pull request merged**
