### PR TITLE
Demo mode that mocks live bus location

### LINKED ISSUE #65: Mock live location

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by heinoapt** [comment]
Looks great! I'll merge this.

**Comment by antti-TIEA4** [comment]
Daaamn :smile: I was just rebasing your PR and was planning to next rebase these on top of that but now this changes things.

**Comment by heinoapt** [comment]
Damn, sorry! Drop me a line next time!

**Comment by antti-TIEA4** [comment]
It's good, I should have been more clear what I was going to do

**Pull request merged**
