### PR TITLE
replace key filed with my google api key

### PR DESCRIPTION
**Pull request by Mxdcq**

### CODE REVIEW

**Comment by antti-TIEA4** [comment]
Hmm... I thought we agreed on Slack that this is not what we want to do?

Also please avoid pushing directly to this repository. It will clutter the branches. You should only push to your fork like in the guide :smiley:

**Comment by Mxdcq** [comment]
Oh, I just followed the steps you taught me

**Comment by antti-TIEA4** [comment]
You pushed to `upstream`. You should push to `origin`. :D 

To avoid this in the future, please run:
```
git remote set-url --push upstream PUSHING-DIRECTLY-TO-UPSTREAM-IS-BAD-MMKAY
```

**Comment by Mxdcq** [comment]
i think i pushed to origin.
`upcoming git:(api_key) git push origin api_key`

**Comment by antti-TIEA4** [comment]
Then you don't have upstream set. We went through this two weeks ago. Have you reset your repository and settings in the mean time?

**Comment by Mxdcq** [comment]
Yes. I deleted the repository and cloned again. 
Then I run:
`git remote add upstream https://github.com/APT-project/pessimist_weather/upcoming.git`

**Comment by antti-TIEA4** [comment]
> Yes. I deleted the repository and cloned again. 
> Then I run:
> `git remote add upstream https://github.com/APT-project/pessimist_weather/upcoming.git`

It should be `upcoming`, not `pessimist_weather` :wink:

**Comment by Mxdcq** [comment]
`git remote add upstream https://github.com/APT-project/upcoming.git`
I just copy paste.
This one is correct?

**Comment by antti-TIEA4** [comment]
yes :+1:

**Comment by Mxdcq** [comment]
Let's move on issue #9

**Pull request merged**
