### PR TITLE
Fix lazy googlelibs

### PR DESCRIPTION
**Pull request by Pikkuninja**
The old async/lazy GoogleMapsApiProvider was a bit busted, as the $get function where it did the loading was actually called during Angular bootstrapping. I moved the loading to happen in a function, and the return value of $get is now an object that can call that function. Also tweaked its name a bit.

### CODE REVIEW

**Comment by antti-TIEA4** [comment]
Thanks, in 8dfcfba20d634815da53c64d214de331be6e11b2

**Comment by antti-TIEA4** [comment]
I did this manually to drop the merge commit https://github.com/APT-project/upcoming/pull/31/commits/1d2bc0f5aca71dc8495ef016b6c220032798f8f7

When you create a new branch, does Git Extensions first update the master and then create the branch based on that, or does it update after creating the new branch? That merge commit seems to indicate the latter?

**Comment by Pikkuninja** [comment]
For some reason the create branch option in Git Extensions always has that "commit" that shows where it was branched off. Don't really know how to get rid of that, I always create the new branches off of master that where I've fetched&merged all the changes from github...

**Comment by antti-TIEA4** [comment]
Hmm... That merge commit had the parent commits d48524a and 39666b3. So it looks like Git Extensions created ("merged") the new branch based on those two. It should have just branched off of 39666b3 without any merging. I can't wrap my head around why it would want to use d48524a? :D 
Well, in any case it's good now :)

**Pull request closed without merging**
